# Generated by Django 4.0.3 on 2022-03-24 11:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('surname', models.CharField(max_length=30)),
                ('card', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='infoEmployee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.CharField(max_length=2000, null=True)),
                ('pros', models.CharField(max_length=500, null=True)),
                ('properties', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='Information.employee')),
            ],
        ),
    ]
