# Generated by Django 4.0.3 on 2022-04-27 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Information', '0002_alter_employee_card_alter_infoemployee_note_trained'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='info',
            field=models.CharField(default=True, max_length=5000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employee',
            name='merit',
            field=models.CharField(default=True, max_length=2000),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='employee',
            name='card',
            field=models.IntegerField(),
        ),
        migrations.DeleteModel(
            name='infoEmployee',
        ),
    ]
