# Generated by Django 4.0.3 on 2022-04-29 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Information', '0003_employee_info_employee_merit_alter_employee_card_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='info',
            field=models.CharField(max_length=5000, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='merit',
            field=models.CharField(max_length=2000, null=True),
        ),
    ]
