# Generated by Django 4.0.3 on 2022-05-05 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Information', '0004_alter_employee_info_alter_employee_merit'),
    ]

    operations = [
        migrations.AddField(
            model_name='trained',
            name='done',
            field=models.BooleanField(null=True),
        ),
    ]
