# Generated by Django 4.0.3 on 2022-05-05 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Information', '0005_trained_done'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trained',
            name='traineds',
        ),
        migrations.AddField(
            model_name='trained',
            name='name',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
