# Generated by Django 4.0.3 on 2022-05-05 10:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Information', '0007_remove_trained_properties_alter_trained_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='trained',
            name='trained',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Information.employee'),
        ),
    ]
