# Generated by Django 4.0.3 on 2022-05-05 12:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Information', '0010_remove_employee_trained_employee_trained'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='trained',
        ),
        migrations.AddField(
            model_name='trained',
            name='trained',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Information.employee'),
        ),
    ]
