# Generated by Django 4.0.3 on 2022-05-05 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Information', '0011_remove_employee_trained_trained_trained'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trained',
            name='trained',
        ),
        migrations.AddField(
            model_name='trained',
            name='trained',
            field=models.ManyToManyField(to='Information.employee'),
        ),
    ]
