# Generated by Django 4.0.3 on 2022-05-12 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Information', '0017_remove_trained_trained_employee_trained'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='info',
            field=models.CharField(max_length=10000, null=True),
        ),
    ]
