# Generated by Django 4.0.3 on 2022-06-22 13:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Information', '0018_alter_employee_info'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='trained',
        ),
        migrations.AddField(
            model_name='employee',
            name='trained',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Information.trained'),
        ),
    ]
